build(deps): revert package-lock re-generation (#9779)
**Related Issue:** #9774

## Summary

Revert the package-lock.json changes in the above PR due to new errors:

```
calcite-design-system/dev/packages/calcite-components/support/generateT9nTypes.ts:1
import globby from "globby";
       ^

SyntaxError: The requested module 'globby' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.1
npm ERR! Lifecycle script `util:generate-t9n-types` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @esri/calcite-components@2.11.0-next.7
npm ERR! Lifecycle script `util:prep-build-reqs` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @esri/calcite-components@2.11.0-next.7
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @esri/calcite-components@2.11.0-next.7
```