ci: resolve e2e errors due to updated actions runner (#11315)
**Related Issue:** https://github.com/actions/runner-images/issues/10636

## Summary

GitHub just updated the `ubuntu-latest` action runner to point to
`v24.04`, which is causing a Puppeteer error:


```text
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Failed to launch the browser process!
[0115/215319.789774:FATAL:zygote_host_impl_linux.cc(128)] No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor, see https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md. Otherwise seehttps://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the (older) SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
 
 
 TROUBLESHOOTING: https://pptr.dev/troubleshooting
```

Downgrading the impacted workflows to `ubuntu-22.04` for now.

ref:
https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md