build: recreate lockfile due to build errors (#9790)
**Related Issue:** N/A

## Summary

Recreates lockfile to fix the following build error:

```bash
➜ calcite-design-system (dev) ✗ npm i && npm run build
npm WARN deprecated @types/prettier@3.0.0: This is a stub types definition. prettier provides its own type definitions, so you do not need this installed.
npm ERR! code 1
npm ERR! path /Users/.../calcite-design-system/node_modules/nx
npm ERR! command failed
npm ERR! command sh -c node ./bin/post-install
npm ERR! /Users/.../calcite-design-system/node_modules/nx/src/native/native-bindings.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR!
npm ERR! Error: Cannot find module '@nx/nx-darwin-arm64'
npm ERR! Require stack:
npm ERR! - /Users/.../calcite-design-system/node_modules/nx/src/native/index.js
npm ERR! - /Users/.../calcite-design-system/node_modules/nx/src/hasher/node-task-hasher-impl.js
npm ERR! - /Users/.../calcite-design-system/node_modules/nx/src/hasher/task-hasher.js
npm ERR! - /Users/.../calcite-design-system/node_modules/nx/src/hasher/hash-task.js
npm ERR! - /Users/.../calcite-design-system/node_modules/nx/src/tasks-runner/run-command.js
npm ERR! - /Users/.../calcite-design-system/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js
npm ERR! - /Users/.../calcite-design-system/node_modules/nx/bin/post-install.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
npm ERR!     at Function.resolve (node:internal/modules/helpers:190:19)
npm ERR!     at Module._load (/Users/.../calcite-design-system/node_modules/nx/src/native/index.js:53:36)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1231:19)
npm ERR!     at require (node:internal/modules/helpers:179:18)
npm ERR!     at Object.<anonymous> (/Users/.../calcite-design-system/node_modules/nx/src/native/native-bindings.js:135:29)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1369:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1206:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1022:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/.../calcite-design-system/node_modules/nx/src/native/index.js',
npm ERR!     '/Users/.../calcite-design-system/node_modules/nx/src/hasher/node-task-hasher-impl.js',
npm ERR!     '/Users/.../calcite-design-system/node_modules/nx/src/hasher/task-hasher.js',
npm ERR!     '/Users/.../calcite-design-system/node_modules/nx/src/hasher/hash-task.js',
npm ERR!     '/Users/.../calcite-design-system/node_modules/nx/src/tasks-runner/run-command.js',
npm ERR!     '/Users/.../calcite-design-system/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js',
npm ERR!     '/Users/.../calcite-design-system/node_modules/nx/bin/post-install.js'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v20.12.1
```