ci: additional changes to the next/rc deployment scripts (#8165)
**Related Issue:** #7526

## Summary

Additional changes to the deployment scripts:

- make sure the commit message has the proper release target via a
script argument
- make sure lerna versioning only occurs from `main` and `rc` branches
- make sure all files are committed, including untracked (e.g. new
changelogs)
- move a closing bracket up a bit so it's not trying to commit for each
output target, which was causing a git error:
    ```
    Error: Command failed: git commit -am 'chore: release next'
fatal: Unable to create
'/home/jamin/dev/work/calcite-design-system/.git/worktree/main/index.lock':
File exists.
    
    Another git process seems to be running in this repository, e.g.
    an editor opened by 'git commit'. Please make sure all processes
    are terminated then try again. If it still fails, a git process
    may have crashed in this repository earlier:
    remove the file manually to continue.
    ```