build: regenerate package lock due to build errors (#9774)
## Summary

Re-generate `package-lock.json` to resolve a build error on osx
machines.

```
Error: Cannot find module '@nx/nx-darwin-arm64'
Require stack:
- /Users/eli97736/Documents/calcite-components/node_modules/nx/src/native/index.js
- /Users/el1i97736/Documents/calcite-components/node_modules/nx/src/hasher/node-task-hasher-impl.js
- /Users/e1i97736/Documents/calcite-components/node_modules/nx/src/hasher/task-hasher.js
- /Users/e1i97736/Documents/calcite-components/node_modules/nx/src/hasher/hash-task.js
- /Users/e1i97736/Documents/calcite-components/node_modules/nx/src/tasks-runner/run-command.js
- /Users/e1i97736/Documents/calcite-components/node_modules/nx/srce/nx-cloud/utilities/get-cloud-options.js
- /Users/e1i97736/Documents/calcite-components/node_modules/nx/bin/post-install.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
at Function.resolve (node:internal/modules/helpers:190:19)
at Module._load (/Users/el1i97736/Documents/calcite-components/node_modules/nx/src/native/index.js:53:36)
at Module.require (node:internal/modules/cjs/loader:1231:19)
at require (node:internal/modules/helpers:179:18)
at Object.<anonymous> (/Users/eli97736/Documents/calcite-components/node_modules/nx/src/native/native-bindings.js:135:29)
at Module._compile (node:internal/modules/cjs/loader:1369:14)
at Module._extensions.js (node:internal/modules/cjs/loader:1427:10)
at Module.load (node:internal/modules/cjs/loader:1206:32)
at Module._load (node:internal/modules/cjs/loader:1022:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/Users/e1i197736/Documents/calcite-components/node_modules/nx/srce/native/index.js',
'/Users/e1i97736/Documents/calcite-components/node_modules/nx/srce/hasher/node-task-hasher-impl.js',
'/Users/e1i97736/Documents/calcite-components/node_modules/nx/srce/hasher/task-hasher.js',
'/Users/e1i97736/Documents/calcite-components/node_modules/nx/src/hasher/hash-task.js',
'/Users/e1i197736/Documents/calcite-components/node_modules/nx/src/tasks-runner/run-command.js',
'/Users/e1i97736/Documents/calcite-components/node_modules/nx/src/nx-cloud/utilities/get-cloud-options.js',
'/Users/e1i97736/Documents/calcite-components/node_modules/nx/bin/post-install.js'
]
}
```

Co-authored-by: Ben Elan <no-reply@benelan.dev>