test: migrate spec tests to browser mode (#13258)
**Related Issue:** N/A

## Summary

Converts spec tests to run in browser mode.

This stems from
https://github.com/Esri/calcite-design-system/pull/13185/ where
Puppeteer-based spec tests appending elements would cause the following
error:

```ts
TypeError: Cannot read properties of undefined (reading 'Symbol(window)')
 ❯ NodeList.forEach ../../node_modules/happy-dom/src/nodes/node/NodeList.ts:210:33
 ❯ node_modules/@arcgis/lumina-compiler/dist/puppeteerTesting/index.js:1126:30
    1124| function pe() {
    1125|   p.extend(ce), V(() => {
    1126|     document.body.childNodes.forEach(R);
       |                              ^
    1127|   });
    1128| }
```

cc @maxpatiiuk 

### Notable changes

* Extract test matchers into their own module to avoid pulling Node
specific context into browser runs
* Refactor `config.ts` to allow clearing resolved config for testing
(addresses
[vitest-dev/vitest#7712](https://github.com/vitest-dev/vitest/issues/7712))
* Fold `dom.e2e.ts` into `dom.browser.spec.ts`  
* Correct `floating-ui` spec assertions since the reference element
remains visible and interactive in browser mode
* Skip number formatting specs for locales `bs` and `mk` to match
current (broken) Chromium behavior
* Extract next tick test util (`waitForNextTick`)

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>