build(components.d.ts): update types for release (#9008)
## Summary

The [release
failed](https://github.com/Esri/calcite-design-system/actions/runs/8445236842/job/23132122216)
due to the `components.d.ts` file being outdated, with the following
error:

```sh
lerna notice cli v7.4.2
lerna info versioning independent
lerna info ci enabled
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M packages/calcite-components/src/components.d.ts
Error: Process completed with exit code 1.
```

I will add an actual fix to the CI in a subsequent PR.